// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="VVAU_hls_0_VVAU_hls_0,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.434000,HLS_SYN_LAT=9222,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=99,HLS_SYN_LUT=281,HLS_VERSION=2022_2}" *)

module VVAU_hls_0 (
        ap_clk,
        ap_rst_n,
        in0_V_TVALID,
        weights_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        weights_V_TDATA,
        weights_V_TREADY,
        out_V_TDATA,
        out_V_TVALID
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter3_fsm_state4 = 2'd2;
parameter    ap_ST_iter4_fsm_state5 = 2'd2;
parameter    ap_ST_iter5_fsm_state6 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;
parameter    ap_ST_iter3_fsm_state0 = 2'd1;
parameter    ap_ST_iter4_fsm_state0 = 2'd1;
parameter    ap_ST_iter5_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst_n;
input   in0_V_TVALID;
input   weights_V_TVALID;
input   out_V_TREADY;
input  [7:0] in0_V_TDATA;
output   in0_V_TREADY;
input  [7:0] weights_V_TDATA;
output   weights_V_TREADY;
output  [23:0] out_V_TDATA;
output   out_V_TVALID;

 reg    ap_rst_n_inv;
reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
wire   [0:0] icmp_ln225_fu_98_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [1:0] ap_CS_iter1_fsm;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_CS_iter1_fsm_state2;
reg   [1:0] ap_CS_iter2_fsm;
reg   [0:0] icmp_ln225_reg_202;
reg   [0:0] icmp_ln225_reg_202_pp0_iter3_reg;
reg   [0:0] icmp_ln266_reg_231;
reg    ap_predicate_op52_write_state5;
reg    ap_block_state5_pp0_stage0_iter4;
reg    ap_block_state5_io;
reg   [1:0] ap_CS_iter4_fsm;
wire    ap_CS_iter4_fsm_state5;
reg    ap_block_state4_pp0_stage0_iter3;
reg   [1:0] ap_CS_iter3_fsm;
wire    ap_CS_iter3_fsm_state4;
reg    ap_block_state3_pp0_stage0_iter2;
wire    ap_CS_iter2_fsm_state3;
reg   [1:0] ap_CS_iter5_fsm;
reg   [0:0] icmp_ln225_reg_202_pp0_iter4_reg;
reg   [0:0] icmp_ln266_reg_231_pp0_iter4_reg;
reg    ap_predicate_op55_write_state6;
wire    regslice_both_out_V_U_apdone_blk;
reg    ap_block_state6_pp0_stage0_iter5;
reg    ap_block_state6_io;
wire    ap_CS_iter5_fsm_state6;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
reg    in0_V_TDATA_blk_n;
reg    weights_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
reg   [0:0] icmp_ln225_reg_202_pp0_iter1_reg;
reg   [0:0] icmp_ln225_reg_202_pp0_iter2_reg;
reg   [7:0] inElem_reg_206;
reg  signed [7:0] W_packed_V_reg_211;
wire   [0:0] icmp_ln266_fu_147_p2;
reg   [13:0] i_fu_54;
wire   [13:0] i_2_fu_104_p2;
wire    ap_loop_init;
reg   [13:0] ap_sig_allocacmp_i_1;
reg   [31:0] sf_fu_58;
wire   [31:0] sf_1_fu_141_p2;
reg   [18:0] outElem_m_val_V_1_fu_62;
wire   [18:0] grp_fu_171_p3;
reg   [18:0] ap_sig_allocacmp_outElem_m_val_V_1_load;
wire   [0:0] icmp_ln230_fu_127_p2;
wire  signed [18:0] zext_ln276_fu_163_p0;
wire   [7:0] grp_fu_171_p0;
wire  signed [18:0] grp_fu_171_p2;
reg    grp_fu_171_ce;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg   [1:0] ap_NS_iter3_fsm;
reg   [1:0] ap_NS_iter4_fsm;
reg   [1:0] ap_NS_iter5_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
wire    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
reg    ap_ST_iter3_fsm_state4_blk;
reg    ap_ST_iter4_fsm_state5_blk;
reg    ap_ST_iter5_fsm_state6_blk;
wire    ap_start_int;
wire    ap_ready;
wire    ap_done;
wire    ap_continue_int;
wire    regslice_both_in0_V_U_apdone_blk;
wire   [7:0] in0_V_TDATA_int_regslice;
wire    in0_V_TVALID_int_regslice;
reg    in0_V_TREADY_int_regslice;
wire    regslice_both_in0_V_U_ack_in;
wire    regslice_both_weights_V_U_apdone_blk;
wire   [7:0] weights_V_TDATA_int_regslice;
wire    weights_V_TVALID_int_regslice;
reg    weights_V_TREADY_int_regslice;
wire    regslice_both_weights_V_U_ack_in;
wire   [23:0] out_V_TDATA_int_regslice;
reg    out_V_TVALID_int_regslice;
wire    out_V_TREADY_int_regslice;
wire    regslice_both_out_V_U_vld_out;
wire   [15:0] grp_fu_171_p00;
reg    ap_condition_406;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
#0 ap_CS_iter4_fsm = 2'd1;
#0 ap_CS_iter3_fsm = 2'd1;
#0 ap_CS_iter5_fsm = 2'd1;
end

VVAU_hls_0_mac_muladd_8ns_8s_19s_19_4_1 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 8 ),
    .din2_WIDTH( 19 ),
    .dout_WIDTH( 19 ))
mac_muladd_8ns_8s_19s_19_4_1_U1(
    .clk(ap_clk),
    .reset(ap_rst_n_inv),
    .din0(grp_fu_171_p0),
    .din1(W_packed_V_reg_211),
    .din2(grp_fu_171_p2),
    .ce(grp_fu_171_ce),
    .dout(grp_fu_171_p3)
);

VVAU_hls_0_flow_control_loop_pipe_no_ap_cont flow_control_loop_pipe_no_ap_cont_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(1'b1),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(1'b0),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(1'b0)
);

VVAU_hls_0_regslice_both #(
    .DataWidth( 8 ))
regslice_both_in0_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in0_V_TDATA),
    .vld_in(in0_V_TVALID),
    .ack_in(regslice_both_in0_V_U_ack_in),
    .data_out(in0_V_TDATA_int_regslice),
    .vld_out(in0_V_TVALID_int_regslice),
    .ack_out(in0_V_TREADY_int_regslice),
    .apdone_blk(regslice_both_in0_V_U_apdone_blk)
);

VVAU_hls_0_regslice_both #(
    .DataWidth( 8 ))
regslice_both_weights_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(weights_V_TDATA),
    .vld_in(weights_V_TVALID),
    .ack_in(regslice_both_weights_V_U_ack_in),
    .data_out(weights_V_TDATA_int_regslice),
    .vld_out(weights_V_TVALID_int_regslice),
    .ack_out(weights_V_TREADY_int_regslice),
    .apdone_blk(regslice_both_weights_V_U_apdone_blk)
);

VVAU_hls_0_regslice_both #(
    .DataWidth( 24 ))
regslice_both_out_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(out_V_TDATA_int_regslice),
    .vld_in(out_V_TVALID_int_regslice),
    .ack_in(out_V_TREADY_int_regslice),
    .data_out(out_V_TDATA),
    .vld_out(regslice_both_out_V_U_vld_out),
    .ack_out(out_V_TREADY),
    .apdone_blk(regslice_both_out_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter3_fsm <= ap_ST_iter3_fsm_state0;
    end else begin
        ap_CS_iter3_fsm <= ap_NS_iter3_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter4_fsm <= ap_ST_iter4_fsm_state0;
    end else begin
        ap_CS_iter4_fsm <= ap_NS_iter4_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter5_fsm <= ap_ST_iter5_fsm_state0;
    end else begin
        ap_CS_iter5_fsm <= ap_NS_iter5_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_406)) begin
        if ((icmp_ln225_fu_98_p2 == 1'd0)) begin
            i_fu_54 <= i_2_fu_104_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_54 <= 14'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter3_fsm_state4) & (icmp_ln266_fu_147_p2 == 1'd1) & (icmp_ln225_reg_202_pp0_iter2_reg == 1'd0)) | (~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1)))) begin
        sf_fu_58 <= 32'd0;
    end else if ((~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter3_fsm_state4) & (icmp_ln266_fu_147_p2 == 1'd0) & (icmp_ln225_reg_202_pp0_iter2_reg == 1'd0))) begin
        sf_fu_58 <= sf_1_fu_141_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln225_fu_98_p2 == 1'd0))) begin
        W_packed_V_reg_211 <= weights_V_TDATA_int_regslice;
        inElem_reg_206 <= in0_V_TDATA_int_regslice;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        icmp_ln225_reg_202 <= icmp_ln225_fu_98_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        icmp_ln225_reg_202_pp0_iter1_reg <= icmp_ln225_reg_202;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
        icmp_ln225_reg_202_pp0_iter2_reg <= icmp_ln225_reg_202_pp0_iter1_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
        icmp_ln225_reg_202_pp0_iter3_reg <= icmp_ln225_reg_202_pp0_iter2_reg;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
        icmp_ln225_reg_202_pp0_iter4_reg <= icmp_ln225_reg_202_pp0_iter3_reg;
        icmp_ln266_reg_231_pp0_iter4_reg <= icmp_ln266_reg_231;
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter3_fsm_state4) & (icmp_ln225_reg_202_pp0_iter2_reg == 1'd0))) begin
        icmp_ln266_reg_231 <= icmp_ln266_fu_147_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter4_fsm_state5) & (icmp_ln225_reg_202_pp0_iter3_reg == 1'd0))) begin
        outElem_m_val_V_1_fu_62 <= grp_fu_171_p3;
    end
end

always @ (*) begin
    if ((((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_iter1_fsm_state2_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0))))) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0))))) begin
        ap_ST_iter3_fsm_state4_blk = 1'b1;
    end else begin
        ap_ST_iter3_fsm_state4_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) begin
        ap_ST_iter4_fsm_state5_blk = 1'b1;
    end else begin
        ap_ST_iter4_fsm_state5_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1)))) begin
        ap_ST_iter5_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_iter5_fsm_state6_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln225_fu_98_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 14'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_54;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter4_fsm_state5) & (icmp_ln225_reg_202_pp0_iter3_reg == 1'd0))) begin
        ap_sig_allocacmp_outElem_m_val_V_1_load = grp_fu_171_p3;
    end else begin
        ap_sig_allocacmp_outElem_m_val_V_1_load = outElem_m_val_V_1_fu_62;
    end
end

always @ (*) begin
    if (((~((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter4_fsm_state5)) | (~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter2_fsm_state3)) | (~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter3_fsm_state4)) | (~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
        grp_fu_171_ce = 1'b1;
    end else begin
        grp_fu_171_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln225_fu_98_p2 == 1'd0))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID_int_regslice;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln225_fu_98_p2 == 1'd0))) begin
        in0_V_TREADY_int_regslice = 1'b1;
    end else begin
        in0_V_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b1 == ap_CS_iter4_fsm_state5) & (ap_predicate_op52_write_state5 == 1'b1)) | ((1'b1 == ap_CS_iter5_fsm_state6) & (ap_predicate_op55_write_state6 == 1'b1)))) begin
        out_V_TDATA_blk_n = out_V_TREADY_int_regslice;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter4_fsm_state5) & (ap_predicate_op52_write_state5 == 1'b1))) begin
        out_V_TVALID_int_regslice = 1'b1;
    end else begin
        out_V_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln225_fu_98_p2 == 1'd0))) begin
        weights_V_TDATA_blk_n = weights_V_TVALID_int_regslice;
    end else begin
        weights_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln225_fu_98_p2 == 1'd0))) begin
        weights_V_TREADY_int_regslice = 1'b1;
    end else begin
        weights_V_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & ~(((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0))))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b0 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter3_fsm)
        ap_ST_iter3_fsm_state4 : begin
            if ((~((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) & ~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else if ((~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & ((1'b0 == ap_CS_iter2_fsm_state3) | ((1'b1 == ap_CS_iter2_fsm_state3) & (1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0))))))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end
        end
        ap_ST_iter3_fsm_state0 : begin
            if ((~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state4;
            end else begin
                ap_NS_iter3_fsm = ap_ST_iter3_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter3_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter4_fsm)
        ap_ST_iter4_fsm_state5 : begin
            if ((~((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & ~((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else if ((~((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & ((1'b0 == ap_CS_iter3_fsm_state4) | ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0))))))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end
        end
        ap_ST_iter4_fsm_state0 : begin
            if ((~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter3_fsm_state4))) begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state5;
            end else begin
                ap_NS_iter4_fsm = ap_ST_iter4_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter4_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter5_fsm)
        ap_ST_iter5_fsm_state6 : begin
            if ((~((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))) & ~((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end else if ((~((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))) & ((1'b0 == ap_CS_iter4_fsm_state5) | ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0))))))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state0;
            end else if ((~((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))) & (1'b1 == ap_CS_iter5_fsm_state6) & (icmp_ln225_reg_202_pp0_iter4_reg == 1'd1))) begin
                ap_NS_iter5_fsm = ap_ST_iter0_fsm_state1;
            end else begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end
        end
        ap_ST_iter5_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter4_fsm_state5))) begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state6;
            end else begin
                ap_NS_iter5_fsm = ap_ST_iter5_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter5_fsm = 'bx;
        end
    endcase
end

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

assign ap_CS_iter3_fsm_state4 = ap_CS_iter3_fsm[32'd1];

assign ap_CS_iter4_fsm_state5 = ap_CS_iter4_fsm[32'd1];

assign ap_CS_iter5_fsm_state6 = ap_CS_iter5_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)));
end

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((1'b1 == ap_CS_iter3_fsm_state4) & (1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_state4_pp0_stage0_iter3 = ((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0))));
end

always @ (*) begin
    ap_block_state5_io = ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state5_pp0_stage0_iter4 = ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state6_io = ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1));
end

always @ (*) begin
    ap_block_state6_pp0_stage0_iter5 = ((regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1)));
end

always @ (*) begin
    ap_condition_406 = (~(((1'b1 == ap_CS_iter4_fsm_state5) & ((1'b1 == ap_block_state5_io) | ((ap_predicate_op52_write_state5 == 1'b1) & (out_V_TREADY_int_regslice == 1'b0)))) | ((weights_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)) | ((in0_V_TVALID_int_regslice == 1'b0) & (icmp_ln225_fu_98_p2 == 1'd0)) | ((1'b1 == ap_CS_iter5_fsm_state6) & ((1'b1 == ap_block_state6_io) | (regslice_both_out_V_U_apdone_blk == 1'b1) | ((out_V_TREADY_int_regslice == 1'b0) & (ap_predicate_op55_write_state6 == 1'b1))))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

always @ (*) begin
    ap_predicate_op52_write_state5 = ((icmp_ln266_reg_231 == 1'd1) & (icmp_ln225_reg_202_pp0_iter3_reg == 1'd0));
end

always @ (*) begin
    ap_predicate_op55_write_state6 = ((icmp_ln266_reg_231_pp0_iter4_reg == 1'd1) & (icmp_ln225_reg_202_pp0_iter4_reg == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign grp_fu_171_p0 = grp_fu_171_p00;

assign grp_fu_171_p00 = inElem_reg_206;

assign grp_fu_171_p2 = ((icmp_ln230_fu_127_p2[0:0] == 1'b1) ? 19'd0 : ap_sig_allocacmp_outElem_m_val_V_1_load);

assign i_2_fu_104_p2 = (ap_sig_allocacmp_i_1 + 14'd1);

assign icmp_ln225_fu_98_p2 = ((ap_sig_allocacmp_i_1 == 14'd9216) ? 1'b1 : 1'b0);

assign icmp_ln230_fu_127_p2 = ((sf_fu_58 == 32'd0) ? 1'b1 : 1'b0);

assign icmp_ln266_fu_147_p2 = ((sf_1_fu_141_p2 == 32'd9) ? 1'b1 : 1'b0);

assign in0_V_TREADY = regslice_both_in0_V_U_ack_in;

assign out_V_TDATA_int_regslice = $unsigned(zext_ln276_fu_163_p0);

assign out_V_TVALID = regslice_both_out_V_U_vld_out;

assign sf_1_fu_141_p2 = (sf_fu_58 + 32'd1);

assign weights_V_TREADY = regslice_both_weights_V_U_ack_in;

assign zext_ln276_fu_163_p0 = grp_fu_171_p3;

endmodule //VVAU_hls_0
