// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="FMPadding_Pixel_hls_2_FMPadding_Pixel_hls_2,hls_ip_2022_2,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xczu7ev-ffvc1156-2-e,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=5.382625,HLS_SYN_LAT=7691,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=105,HLS_SYN_LUT=667,HLS_VERSION=2022_2}" *)

module FMPadding_Pixel_hls_2 (
        ap_clk,
        ap_rst_n,
        in0_V_TVALID,
        out_V_TREADY,
        in0_V_TDATA,
        in0_V_TREADY,
        out_V_TDATA,
        out_V_TVALID
);

parameter    ap_ST_iter0_fsm_state1 = 1'd1;
parameter    ap_ST_iter1_fsm_state2 = 2'd2;
parameter    ap_ST_iter2_fsm_state3 = 2'd2;
parameter    ap_ST_iter1_fsm_state0 = 2'd1;
parameter    ap_ST_iter2_fsm_state0 = 2'd1;

input   ap_clk;
input   ap_rst_n;
input   in0_V_TVALID;
input   out_V_TREADY;
input  [7:0] in0_V_TDATA;
output   in0_V_TREADY;
output  [7:0] out_V_TDATA;
output   out_V_TVALID;

 reg    ap_rst_n_inv;
reg   [0:0] ap_CS_iter0_fsm;
wire    ap_CS_iter0_fsm_state1;
wire   [0:0] icmp_ln453_fu_187_p2;
wire   [0:0] select_ln454_fu_285_p3;
reg    ap_predicate_op57_read_state1;
reg    ap_block_state1_pp0_stage0_iter0;
reg   [1:0] ap_CS_iter1_fsm;
reg   [0:0] icmp_ln453_reg_395;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_state2_io;
wire    ap_CS_iter1_fsm_state2;
reg   [1:0] ap_CS_iter2_fsm;
reg   [0:0] icmp_ln453_reg_395_pp0_iter1_reg;
wire    regslice_both_out_V_U_apdone_blk;
reg    ap_block_state3_pp0_stage0_iter2;
reg    ap_block_state3_io;
wire    ap_CS_iter2_fsm_state3;
reg    ap_condition_exit_pp0_iter0_stage0;
reg    ap_ready_int;
reg    in0_V_TDATA_blk_n;
reg    out_V_TDATA_blk_n;
wire   [7:0] ap_phi_reg_pp0_iter0_value_V_1_reg_101;
reg   [7:0] ap_phi_reg_pp0_iter1_value_V_1_reg_101;
reg   [3:0] sf_fu_68;
wire   [3:0] sf_3_fu_313_p3;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_sf_2;
reg   [31:0] xtrig_fu_72;
wire   [31:0] select_ln455_fu_293_p3;
reg   [31:0] ap_sig_allocacmp_xtrig_1;
reg   [8:0] indvar_flatten_fu_76;
wire   [8:0] select_ln455_1_fu_327_p3;
reg   [8:0] ap_sig_allocacmp_indvar_flatten_load;
reg   [31:0] ytrig_fu_80;
wire   [31:0] select_ln453_2_fu_245_p3;
reg   [31:0] ap_sig_allocacmp_ytrig_3;
reg   [12:0] indvar_flatten19_fu_84;
wire   [12:0] add_ln453_fu_193_p2;
reg   [12:0] ap_sig_allocacmp_indvar_flatten19_load;
wire   [31:0] empty_fu_155_p2;
wire   [31:0] ytrig_4_fu_167_p2;
wire   [0:0] icmp_ln464_fu_173_p2;
wire   [0:0] icmp_ln455_fu_199_p2;
wire   [31:0] ytrig_5_fu_179_p3;
wire   [0:0] p_mid115_fu_213_p2;
wire   [0:0] empty_8_fu_161_p2;
wire   [0:0] icmp_ln456_fu_233_p2;
wire   [0:0] xor_ln453_fu_227_p2;
wire   [31:0] select_ln453_fu_205_p3;
wire   [31:0] xtrig_4_fu_253_p2;
wire   [0:0] icmp_ln462_fu_259_p2;
wire   [31:0] xtrig_5_fu_265_p3;
wire   [31:0] p_mid1_fu_273_p2;
wire   [0:0] and_ln453_fu_239_p2;
wire   [0:0] p_mid13_fu_279_p2;
wire   [0:0] select_ln453_1_fu_219_p3;
wire   [0:0] or_ln456_fu_307_p2;
wire   [3:0] add_ln456_fu_301_p2;
wire   [8:0] add_ln455_fu_321_p2;
reg   [0:0] ap_NS_iter0_fsm;
reg   [1:0] ap_NS_iter1_fsm;
reg   [1:0] ap_NS_iter2_fsm;
reg    ap_ST_iter0_fsm_state1_blk;
reg    ap_ST_iter1_fsm_state2_blk;
reg    ap_ST_iter2_fsm_state3_blk;
wire    ap_start_int;
wire    ap_ready;
wire    ap_done;
wire    ap_continue_int;
wire    regslice_both_in0_V_U_apdone_blk;
wire   [7:0] in0_V_TDATA_int_regslice;
wire    in0_V_TVALID_int_regslice;
reg    in0_V_TREADY_int_regslice;
wire    regslice_both_in0_V_U_ack_in;
reg    out_V_TVALID_int_regslice;
wire    out_V_TREADY_int_regslice;
wire    regslice_both_out_V_U_vld_out;
reg    ap_condition_355;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_iter0_fsm = 1'd1;
#0 ap_CS_iter1_fsm = 2'd1;
#0 ap_CS_iter2_fsm = 2'd1;
end

FMPadding_Pixel_hls_2_flow_control_loop_pipe_no_ap_cont flow_control_loop_pipe_no_ap_cont_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .ap_start(1'b1),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(1'b0),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(1'b0)
);

FMPadding_Pixel_hls_2_regslice_both #(
    .DataWidth( 8 ))
regslice_both_in0_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(in0_V_TDATA),
    .vld_in(in0_V_TVALID),
    .ack_in(regslice_both_in0_V_U_ack_in),
    .data_out(in0_V_TDATA_int_regslice),
    .vld_out(in0_V_TVALID_int_regslice),
    .ack_out(in0_V_TREADY_int_regslice),
    .apdone_blk(regslice_both_in0_V_U_apdone_blk)
);

FMPadding_Pixel_hls_2_regslice_both #(
    .DataWidth( 8 ))
regslice_both_out_V_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst_n_inv),
    .data_in(ap_phi_reg_pp0_iter1_value_V_1_reg_101),
    .vld_in(out_V_TVALID_int_regslice),
    .ack_in(out_V_TREADY_int_regslice),
    .data_out(out_V_TDATA),
    .vld_out(regslice_both_out_V_U_vld_out),
    .ack_out(out_V_TREADY),
    .apdone_blk(regslice_both_out_V_U_apdone_blk)
);

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter0_fsm <= ap_ST_iter0_fsm_state1;
    end else begin
        ap_CS_iter0_fsm <= ap_NS_iter0_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter1_fsm <= ap_ST_iter1_fsm_state0;
    end else begin
        ap_CS_iter1_fsm <= ap_NS_iter1_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst_n_inv == 1'b1) begin
        ap_CS_iter2_fsm <= ap_ST_iter2_fsm_state0;
    end else begin
        ap_CS_iter2_fsm <= ap_NS_iter2_fsm;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_355)) begin
        if (((select_ln454_fu_285_p3 == 1'd0) & (icmp_ln453_fu_187_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_value_V_1_reg_101 <= 8'd0;
        end else if (((select_ln454_fu_285_p3 == 1'd1) & (icmp_ln453_fu_187_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_value_V_1_reg_101 <= in0_V_TDATA_int_regslice;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_value_V_1_reg_101 <= ap_phi_reg_pp0_iter0_value_V_1_reg_101;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_355)) begin
        if ((icmp_ln453_fu_187_p2 == 1'd0)) begin
            indvar_flatten19_fu_84 <= add_ln453_fu_193_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten19_fu_84 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_355)) begin
        if ((icmp_ln453_fu_187_p2 == 1'd0)) begin
            indvar_flatten_fu_76 <= select_ln455_1_fu_327_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_76 <= 9'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_355)) begin
        if ((icmp_ln453_fu_187_p2 == 1'd0)) begin
            sf_fu_68 <= sf_3_fu_313_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            sf_fu_68 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_355)) begin
        if ((icmp_ln453_fu_187_p2 == 1'd0)) begin
            xtrig_fu_72 <= select_ln455_fu_293_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            xtrig_fu_72 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_355)) begin
        if ((icmp_ln453_fu_187_p2 == 1'd0)) begin
            ytrig_fu_80 <= select_ln453_2_fu_245_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            ytrig_fu_80 <= 32'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln453_reg_395_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln453_reg_395 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((ap_predicate_op57_read_state1 == 1'b1) & (in0_V_TVALID_int_regslice == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        icmp_ln453_reg_395 <= icmp_ln453_fu_187_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((~((1'b1 == ap_block_state2_io) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln453_reg_395_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((icmp_ln453_reg_395 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        icmp_ln453_reg_395_pp0_iter1_reg <= icmp_ln453_reg_395;
    end
end

always @ (*) begin
    if (((ap_predicate_op57_read_state1 == 1'b1) & (in0_V_TVALID_int_regslice == 1'b0))) begin
        ap_ST_iter0_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_iter0_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_block_state2_io) | ((icmp_ln453_reg_395 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) begin
        ap_ST_iter1_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_iter1_fsm_state2_blk = 1'b0;
    end
end

always @ (*) begin
    if (((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln453_reg_395_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) begin
        ap_ST_iter2_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_iter2_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln453_reg_395_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln453_reg_395 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((ap_predicate_op57_read_state1 == 1'b1) & (in0_V_TVALID_int_regslice == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1) & (icmp_ln453_fu_187_p2 == 1'd1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln453_reg_395_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln453_reg_395 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((ap_predicate_op57_read_state1 == 1'b1) & (in0_V_TVALID_int_regslice == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten19_load = 13'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten19_load = indvar_flatten19_fu_84;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_indvar_flatten_load = 9'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_76;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_sf_2 = 4'd0;
    end else begin
        ap_sig_allocacmp_sf_2 = sf_fu_68;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_xtrig_1 = 32'd0;
    end else begin
        ap_sig_allocacmp_xtrig_1 = xtrig_fu_72;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_ytrig_3 = 32'd0;
    end else begin
        ap_sig_allocacmp_ytrig_3 = ytrig_fu_80;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_iter0_fsm_state1) & (ap_predicate_op57_read_state1 == 1'b1))) begin
        in0_V_TDATA_blk_n = in0_V_TVALID_int_regslice;
    end else begin
        in0_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln453_reg_395_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln453_reg_395 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((ap_predicate_op57_read_state1 == 1'b1) & (in0_V_TVALID_int_regslice == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1) & (ap_predicate_op57_read_state1 == 1'b1))) begin
        in0_V_TREADY_int_regslice = 1'b1;
    end else begin
        in0_V_TREADY_int_regslice = 1'b0;
    end
end

always @ (*) begin
    if ((((icmp_ln453_reg_395_pp0_iter1_reg == 1'd0) & (1'b1 == ap_CS_iter2_fsm_state3)) | ((icmp_ln453_reg_395 == 1'd0) & (1'b1 == ap_CS_iter1_fsm_state2)))) begin
        out_V_TDATA_blk_n = out_V_TREADY_int_regslice;
    end else begin
        out_V_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((1'b1 == ap_block_state2_io) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln453_reg_395_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((icmp_ln453_reg_395 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0))) & (icmp_ln453_reg_395 == 1'd0) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
        out_V_TVALID_int_regslice = 1'b1;
    end else begin
        out_V_TVALID_int_regslice = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_iter0_fsm)
        ap_ST_iter0_fsm_state1 : begin
            ap_NS_iter0_fsm = ap_ST_iter0_fsm_state1;
        end
        default : begin
            ap_NS_iter0_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter1_fsm)
        ap_ST_iter1_fsm_state2 : begin
            if ((~((1'b1 == ap_block_state2_io) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln453_reg_395_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((icmp_ln453_reg_395 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0))) & ~((ap_predicate_op57_read_state1 == 1'b1) & (in0_V_TVALID_int_regslice == 1'b0)) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else if ((~((1'b1 == ap_block_state2_io) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln453_reg_395_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((icmp_ln453_reg_395 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0))) & ((1'b0 == ap_CS_iter0_fsm_state1) | ((1'b1 == ap_CS_iter0_fsm_state1) & (ap_predicate_op57_read_state1 == 1'b1) & (in0_V_TVALID_int_regslice == 1'b0))))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end
        end
        ap_ST_iter1_fsm_state0 : begin
            if ((~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln453_reg_395_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln453_reg_395 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((ap_predicate_op57_read_state1 == 1'b1) & (in0_V_TVALID_int_regslice == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1))) begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state2;
            end else begin
                ap_NS_iter1_fsm = ap_ST_iter1_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter1_fsm = 'bx;
        end
    endcase
end

always @ (*) begin
    case (ap_CS_iter2_fsm)
        ap_ST_iter2_fsm_state3 : begin
            if ((~((1'b1 == ap_block_state2_io) | ((icmp_ln453_reg_395 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0))) & ~((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln453_reg_395_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else if ((~((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln453_reg_395_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0))) & ((1'b0 == ap_CS_iter1_fsm_state2) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln453_reg_395 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0))))))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end else if ((~((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln453_reg_395_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0))) & (icmp_ln453_reg_395_pp0_iter1_reg == 1'd1) & (1'b1 == ap_CS_iter2_fsm_state3))) begin
                ap_NS_iter2_fsm = ap_ST_iter0_fsm_state1;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end
        end
        ap_ST_iter2_fsm_state0 : begin
            if ((~((1'b1 == ap_block_state2_io) | ((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln453_reg_395_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((icmp_ln453_reg_395 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0))) & (1'b1 == ap_CS_iter1_fsm_state2))) begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state3;
            end else begin
                ap_NS_iter2_fsm = ap_ST_iter2_fsm_state0;
            end
        end
        default : begin
            ap_NS_iter2_fsm = 'bx;
        end
    endcase
end

assign add_ln453_fu_193_p2 = (ap_sig_allocacmp_indvar_flatten19_load + 13'd1);

assign add_ln455_fu_321_p2 = (ap_sig_allocacmp_indvar_flatten_load + 9'd1);

assign add_ln456_fu_301_p2 = (ap_sig_allocacmp_sf_2 + 4'd1);

assign and_ln453_fu_239_p2 = (xor_ln453_fu_227_p2 & icmp_ln456_fu_233_p2);

assign ap_CS_iter0_fsm_state1 = ap_CS_iter0_fsm[32'd0];

assign ap_CS_iter1_fsm_state2 = ap_CS_iter1_fsm[32'd1];

assign ap_CS_iter2_fsm_state3 = ap_CS_iter2_fsm[32'd1];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_predicate_op57_read_state1 == 1'b1) & (in0_V_TVALID_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state2_io = ((icmp_ln453_reg_395 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = ((icmp_ln453_reg_395 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3_io = ((icmp_ln453_reg_395_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0));
end

always @ (*) begin
    ap_block_state3_pp0_stage0_iter2 = ((regslice_both_out_V_U_apdone_blk == 1'b1) | ((icmp_ln453_reg_395_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)));
end

always @ (*) begin
    ap_condition_355 = (~(((1'b1 == ap_CS_iter2_fsm_state3) & ((regslice_both_out_V_U_apdone_blk == 1'b1) | (1'b1 == ap_block_state3_io) | ((icmp_ln453_reg_395_pp0_iter1_reg == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((1'b1 == ap_CS_iter1_fsm_state2) & ((1'b1 == ap_block_state2_io) | ((icmp_ln453_reg_395 == 1'd0) & (out_V_TREADY_int_regslice == 1'b0)))) | ((ap_predicate_op57_read_state1 == 1'b1) & (in0_V_TVALID_int_regslice == 1'b0))) & (1'b1 == ap_CS_iter0_fsm_state1));
end

assign ap_phi_reg_pp0_iter0_value_V_1_reg_101 = 'bx;

always @ (*) begin
    ap_predicate_op57_read_state1 = ((select_ln454_fu_285_p3 == 1'd1) & (icmp_ln453_fu_187_p2 == 1'd0));
end

always @ (*) begin
    ap_rst_n_inv = ~ap_rst_n;
end

assign empty_8_fu_161_p2 = ((empty_fu_155_p2 == 32'd0) ? 1'b1 : 1'b0);

assign empty_fu_155_p2 = (ap_sig_allocacmp_ytrig_3 | ap_sig_allocacmp_xtrig_1);

assign icmp_ln453_fu_187_p2 = ((ap_sig_allocacmp_indvar_flatten19_load == 13'd7688) ? 1'b1 : 1'b0);

assign icmp_ln455_fu_199_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 9'd248) ? 1'b1 : 1'b0);

assign icmp_ln456_fu_233_p2 = ((ap_sig_allocacmp_sf_2 == 4'd8) ? 1'b1 : 1'b0);

assign icmp_ln462_fu_259_p2 = ((xtrig_4_fu_253_p2 == 32'd2) ? 1'b1 : 1'b0);

assign icmp_ln464_fu_173_p2 = ((ytrig_4_fu_167_p2 == 32'd2) ? 1'b1 : 1'b0);

assign in0_V_TREADY = regslice_both_in0_V_U_ack_in;

assign or_ln456_fu_307_p2 = (icmp_ln455_fu_199_p2 | and_ln453_fu_239_p2);

assign out_V_TVALID = regslice_both_out_V_U_vld_out;

assign p_mid115_fu_213_p2 = ((ytrig_5_fu_179_p3 == 32'd0) ? 1'b1 : 1'b0);

assign p_mid13_fu_279_p2 = ((p_mid1_fu_273_p2 == 32'd0) ? 1'b1 : 1'b0);

assign p_mid1_fu_273_p2 = (xtrig_5_fu_265_p3 | select_ln453_2_fu_245_p3);

assign select_ln453_1_fu_219_p3 = ((icmp_ln455_fu_199_p2[0:0] == 1'b1) ? p_mid115_fu_213_p2 : empty_8_fu_161_p2);

assign select_ln453_2_fu_245_p3 = ((icmp_ln455_fu_199_p2[0:0] == 1'b1) ? ytrig_5_fu_179_p3 : ap_sig_allocacmp_ytrig_3);

assign select_ln453_fu_205_p3 = ((icmp_ln455_fu_199_p2[0:0] == 1'b1) ? 32'd0 : ap_sig_allocacmp_xtrig_1);

assign select_ln454_fu_285_p3 = ((and_ln453_fu_239_p2[0:0] == 1'b1) ? p_mid13_fu_279_p2 : select_ln453_1_fu_219_p3);

assign select_ln455_1_fu_327_p3 = ((icmp_ln455_fu_199_p2[0:0] == 1'b1) ? 9'd1 : add_ln455_fu_321_p2);

assign select_ln455_fu_293_p3 = ((and_ln453_fu_239_p2[0:0] == 1'b1) ? xtrig_5_fu_265_p3 : select_ln453_fu_205_p3);

assign sf_3_fu_313_p3 = ((or_ln456_fu_307_p2[0:0] == 1'b1) ? 4'd1 : add_ln456_fu_301_p2);

assign xor_ln453_fu_227_p2 = (icmp_ln455_fu_199_p2 ^ 1'd1);

assign xtrig_4_fu_253_p2 = (select_ln453_fu_205_p3 + 32'd1);

assign xtrig_5_fu_265_p3 = ((icmp_ln462_fu_259_p2[0:0] == 1'b1) ? 32'd0 : xtrig_4_fu_253_p2);

assign ytrig_4_fu_167_p2 = (ap_sig_allocacmp_ytrig_3 + 32'd1);

assign ytrig_5_fu_179_p3 = ((icmp_ln464_fu_173_p2[0:0] == 1'b1) ? 32'd0 : ytrig_4_fu_167_p2);

endmodule //FMPadding_Pixel_hls_2
